openapi: 3.0.1
info:
  title: SpectrumX Core API
  description: Access to SpectrumX's intuitive reflex core and entity management.
  version: 0.1.0
servers:
  - url: https://endergoran.github.io/SpectrumX-core

paths:
  /core:
    get:
      summary: Retrieve core JSON
      operationId: getCore
      responses:
        '200':
          description: Core JSON content
          content:
            application/json:
              schema:
                type: object

  /entity:
    post:
      summary: Create a new entity
      operationId: createEntity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entity'
      responses:
        '201':
          description: Entity successfully created

  /entity/{id}:
    get:
      summary: Get entity by ID
      operationId: getEntity
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Entity retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity'

    put:
      summary: Update an existing entity
      operationId: updateEntity
      parameters:
        - name: id
          in: path
          required: true
